### ISSUE TITLE
regexp error in the litetabletdetectionPlus.config file

### ISSUE THREAD

**Issue by guizdiabolik** [ifuschini/AMFPlus#4]
An issue in the litetabletdetectionPlus.config : the double slash in the regexp before "nexus 10"

the issue :
puffin(.*)[0-9]at$|sm-\t[0-9][0-9]||nexus 10|nexus 7|sm\-t210,tablet|pad| tab|flyer|wpad|froyo|xoom|mz6| a500 | a501 |streak|transformer|hri66|gt\-p[0-9]| k00[a-zA-Z]|gt\-p75|sch\-i800|playbook|manta B|kindle|msie [0-9].+[0-9]; arm; trident|mozilla/[0-9].+[0-9] \(tablet

the fix :
puffin(.*)[0-9]at$|sm-\t[0-9][0-9]|nexus 10|nexus 7|sm\-t210,tablet|pad| tab|flyer|wpad|froyo|xoom|mz6| a500 | a501 |streak|transformer|hri66|gt\-p[0-9]| k00[a-zA-Z]|gt\-p75|sch\-i800|playbook|manta B|kindle|msie [0-9].+[0-9]; arm; trident|mozilla/[0-9].+[0-9] \(tablet

thank to [Healkiss](https://github.com/Healkiss)

**Comment by ifuschini** [comment]
Thanks, update with your fix
